final url = 'http://10.210.60.215:8081/';
final registerion = url + "registration";
final login = url + "login";
final lottos = url + "lottos";
final winning = url + "winning";
final users = url + "user/";
final ticket = url + "ticket/";
final lottoSearch = url + "lotto/";
final winn = url + "check-priz";